apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 1.15.1
      helm:
        releaseName: vault
        valueFiles:
          - $values/system/vault/helm/vault.values.yaml
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
    - chart: vault-config-operator
      repoURL: https://redhat-cop.github.io/vault-config-operator
      targetRevision: 0.8.24
      helm:
        releaseName: vault-config-operator
        valueFiles:
          - $values/system/vault/helm/vault-config-operator.values.yaml
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
    project: platforme-cedille