# moves the grav skeleton to the storage of grav-pvc (overwriting whatever is there)
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: grav-init
spec:
  # use kubectl create job --from=cronjob/<cronjob-name> <job-name>
  # to initialize site
  #TODO #HACK
  schedule: "1 * * * *" #suspended
  startingDeadlineSeconds: 100
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          name: grav-init
        spec:
          containers:
          - name: grav-init
            image: grav-init
            args: ["rsync", "-av", "grav/", "/var/www/html"]
            volumeMounts:
              - name: grav-pvc
                mountPath: /var/www/html
            resources:
              requests:
                memory: "40Mi"
                cpu: "200m"
              limits:
                memory: "100Mi"
                cpu: "500m"
          volumes:
          - name: grav-pvc
            persistentVolumeClaim:
              claimName: grav-pvc
          restartPolicy: Never
      activeDeadlineSeconds: 1200
      backoffLimit: 0