apiVersion: apps/v1
kind: Deployment
metadata:
  name: grav-demo
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-template-salt: |
          {{- with secret "kv-system/default_passwords/grav" }}
          salt: {{ .Data.salt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-admin_pwd: |
          {{- with secret "kv-system/default_passwords/grav" }}
          state: enabled
          email: admin@cedille.club
          fullname: admin
          title: Administrator
          access:
            admin:
              login: true
              super: true
            site:
              login: true
          password: {{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-gitsync: |
          {{- with secret "github/token/grav-demo" -}}
          enabled: true
          folders:
            - pages
            - plugins
            - themes
            - config
          SyncNotice: null
          sync:
            on_save: true
            on_delete: true
            on_media: true
            cron_enable: true
            cron_at: '*/10 * * * *'
          local_repository: null
          repository: 'https://github.com/ClubCedille/grav-sync-example.git'
          no_user: '0'
          user: x-access-token
          password: {{ .Data.token }}
          webhook_enabled: '0'
          branch: master
          remote:
            name: origin
            branch: master
          git:
            author: gitsync
            message: '(Grav GitSync) Automatic Commit'
            name: GitSync
            email: git-sync@trilby.media
            bin: git
            ignore: null
            private_key: null
          logging: true
          {{- end }}
        vault.hashicorp.com/role: 'secret-reader'