apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-cedille
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-cedille
  template:
    metadata:
      labels:
        app: wiki-cedille
    spec:
      containers:
        - name: wiki-cedille
          image: ghcr.io/clubcedille/wiki-cedille:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
