apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-admin
subjects:
- kind: User
  name: USERNAME
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sandbox-admin
  apiGroup: rbac.authorization.k8s.io