apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      valueFiles:
      - "cert-manager-config.yaml"
      parameters: 
        - name: installCRDs # Not recommended for prod installs according to: https://cert-manager.io/docs/installation/helm/
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true