apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-csi
  namespace: argocd
  argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - chart: secrets-store-csi-driver
      repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      targetRevision: 1.3.4
      helm:
        releaseName: secrets-store-csi-driver
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
    project: platforme-cedille