apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: edvintest-grav
spec:
  authentication: 
    path: kubernetes
    role: config-admin
  path: github
  repositories:
  - edvin.cedille.club
  organizationName: ClubCedille
