apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: integrale-grav
spec:
  authentication: 
    path: kubernetes
    role: config-admin
  path: github
  repositories:
  - integrale.etsmtl.ca
  organizationName: ClubCedille
