apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewall
  template:
    metadata:
      labels:
        app: kubewall
    spec:
      serviceAccountName: kubewall-admin
      containers:
        - name: kubewall
          image: ghcr.io/kubewall/kubewall:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault