apiVersion: apps/v1
kind: Deployment
metadata:
  name: trema
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'secret-reader'
        vault.hashicorp.com/agent-inject-template-mongo_pwd: |
          {{- with secret "kv/trema/default/mongo" -}}
          password: {{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-discord_token: |
          {{- with secret "kv/trema/default/trema" -}}
          token: {{ .Data.data.token }}
          {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'secret-reader'
        vault.hashicorp.com/agent-inject-template-mongo_pwd: |
          {{- with secret "kv/trema/default/mongo" -}}
          password: {{ .Data.data.password }}
          {{- end }}