apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # System
  - ../../system/crossplane/
  - ../../system/vault/
  - ../../system/grafana/
  - ../../system/clickhouse/
  - ../../system/cert-manager/
  # - ../../system/vcluster/
  - ../../system/argocd/
  - ../../system/secret-store-csi/
  - ../../system/opentelemetry-operator/
  - ../../system/gateway-api/
  - ../../system/kubevirt/
  - ../../system/kuma/
  - ../../system/merbridge/
  - ../../system/kubevious/
  #- ../../system/pixie/
  # Workload
  - ../samples/kustomize-example-app/
  - ../samples/opentelemetry-demo/
  - ../samples/grav-demo/
  - ../calidum-rotae/
  - ../ganache/
  - ../blockscout/
  - ../acets/grav/
  # ... other apps ...

patches:
  # This patch will set the destination cluster for Applications
  - target:
      kind: Application
      labelSelector: "environment=staging"
    patch: |-
      - op: add
        path: /spec/destination/server
        value: https://vcluster-staging.vcluster-staging.svc.cluster.local
  - target:
      kind: Application
      labelSelector: "environment in (prod, production)"
    patch: |-
      - op: add
        path: /spec/destination/server
        value: https://vcluster-prod.vcluster-prod.svc.cluster.local
  - target:
      kind: Application
      labelSelector: "environment=sandbox"
    patch: |-
      - op: add
        path: /spec/destination/server
        value: https://vcluster-sandbox.vcluster-sandbox.svc.cluster.local
  ###
  # This patch sets common settings for Applications.
  - target:
      kind: Application
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-used
        finalizers:
        - resources-finalizer.argocd.argoproj.io
      spec:
        syncPolicy:
          automated:
            selfHeal: true
