apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../system/crossplane/
  - ../../system/grafana/
  - ../../system/vcluster/
  - ../samples/kustomize-example-app/
  # ... other apps ...