apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # System
  - ../../system/crossplane/
  - ../../system/vault
  - ../../external-dns/
  - ../../system/grafana/
  - ../../system/clickhouse/
  - ../../system/cert-manager/
  - ../../system/argocd/
  - ../../system/opentelemetry/
  - ../../system/gateway-api/
  - ../../system/kubevirt/
  - ../../system/kuma/
  - ../../system/merbridge/
  # Workload
  - ../samples/kustomize-example-app/
  - ../samples/opentelemetry-demo/
  - ../samples/grav-demo/
  # ... other apps ...

patches:
  - target:
      kind: Application
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-used
        finalizers:
        - resources-finalizer.argocd.argoproj.io
      spec:
        syncPolicy:
          automated:
            selfHeal: true