apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # System
  - ../../system/crossplane/
  - ../../system/grafana/
  # Workload
  - ../samples/kustomize-example-app/

patches:
  - target:
      kind: Application
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-used
        finalizers:
        - resources-finalizer.argocd.argoproj.io
      spec:
        syncPolicy:
          automated:
            selfHeal: true