apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grav-demo
  name: grav-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav-demo
  template:
    metadata:
      labels:
        app: grav-demo
    spec:
      containers:
      - name: grav-demo
        image: clubcedille/grav:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "10m"
            hugepages-2Mi: "2Mi"
          limits:
            memory: "16Mi"
            cpu: "100m"
            hugepages-2Mi: "2Mi"
        volumeMounts:
        - name: grav-storage
          mountPath: /var/www/html
      volumes:
      - name: grav-storage
        persistentVolumeClaim:
          claimName: grav-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1G"

