apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grav-demo
  name: grav-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav-demo
  template:
    metadata:
      labels:
        app: grav-demo
      annotations:
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-template-salt: |
          {{- with secret "kv-system/default_passwords/grav" }}
          salt: {{ .Data.salt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-admin_pwd: |
          {{- with secret "kv-system/default_passwords/grav" }}
          state: enabled
          email: admin@cedille.club
          fullname: admin
          title: Administrator
          access:
            admin:
              login: true
              super: true
            site:
              login: true
          password: {{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-gitsync: |
          {{- with secret "github/token/grav-demo" -}}
          enabled: true
          folders:
            - pages
            - plugins
            - themes
            - config
          SyncNotice: null
          sync:
            on_save: true
            on_delete: true
            on_media: true
            cron_enable: true
            cron_at: '*/10 * * * *'
          local_repository: null
          repository: 'https://github.com/ClubCedille/grav-sync-example.git'
          no_user: '0'
          user: x-access-token
          password: {{ .Data.token }}
          webhook_enabled: '0'
          branch: test
          remote:
            name: origin
            branch: test
          git:
            author: gitsync
            message: '(Grav GitSync) Automatic Commit'
            name: GitSync
            email: git-sync@trilby.media
            bin: git
            ignore: null
            private_key: null
          logging: true
          {{- end }}
        vault.hashicorp.com/role: 'secret-reader'
    spec:
      containers:
      - name: grav-demo
        image: ghcr.io/clubcedille/grav:0.0.7
        imagePullPolicy: Always
        env:
        - name: GIT_VAULT_SECRET
          value: gitsync
        - name: ADMIN_VAULT_SECRET
          value: admin_pwd
        - name: HEAD_BRANCH
          value: test
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: grav-accounts
          mountPath: /var/www/html/user/accounts
        - name: grav-data
          mountPath: /var/www/html/user/data
      # group 33 is www-data
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes:
      - name: grav-accounts
        persistentVolumeClaim:
          claimName: grav-accounts-pvc
      - name: grav-configs
        persistentVolumeClaim:
          claimName: grav-configs-pvc
      - name: grav-data
        persistentVolumeClaim:
          claimName: grav-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-accounts-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-data-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
