apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-app
  annotations:
    namespace: argocd
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: system/crossplane
    targetRevision: HEAD 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true