apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-helm
  namespace: argocd
  argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/ClubCedille/Plateforme-Cedille
      path: system/crossplane/resources
      targetRevision: HEAD 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane
    project: platforme-cedille
  syncPolicy:
    syncOptions:
    - CreateNamespace=true