apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: vcluster-prod
  namespace: argocd
spec:
  destination:
    namespace: vcluster-prod
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: vcluster
      helm:
        releaseName: vcluster-prod
        valueFiles:
        - $values/system/vcluster/helm/common-values.yaml
        - $values/system/vcluster/helm/cert-manager-plugin.yaml
      repoURL: https://charts.loft.sh
      targetRevision: 0.16.4
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true