apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: vcluster
  namespace: argocd
spec:
  destination:
    namespace: vcluster
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: vcluster
      helm:
        releaseName: vcluster-prod
        valueFiles:
        - $values/system/vcluster/helm/common-values.yaml
      repoURL: https://charts.loft.sh
      targetRevision: 0.16.4
    - chart: vcluster
      helm:
        releaseName: vcluster-sandbox
        valueFiles:
        - $values/system/vcluster/helm/common-values.yaml
      repoURL: https://charts.loft.sh
      targetRevision: 0.16.4
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
      targetRevision: feature/vcluster
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true