apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
    project: default
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: system/crossplane/resources
    targetRevision: HEAD 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true