apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grav
  name: grav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav
  template:
    metadata:
      labels:
        app: grav
      annotations:
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'secret-reader'
        vault.hashicorp.com/agent-inject-template-salt: |
          {{- with secret "kv-system/default_passwords/grav" }}
          salt: {{ .Data.salt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-admin_pwd: |
          {{- with secret "kv-system/default_passwords/grav" }}
          state: enabled
          email: sre@cedille.club
          username: sre
          fullname: sre
          title: SRE
          access:
            admin:
              login: true
              super: true
            site:
              login: true
          password: {{ .Data.password }}
          {{- end }}
    spec:
      containers:
      - name: grav
        image: ghcr.io/clubcedille/grav:0.0.7
        imagePullPolicy: Always
        env:
        - name: GIT_VAULT_SECRET
          value: gitsync
        - name: ADMIN_VAULT_SECRET
          value: admin_pwd
        - name: HEAD_BRANCH
          value: master
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: grav-accounts
          mountPath: /var/www/html/user/accounts
        - name: grav-data
          mountPath: /var/www/html/user/data
      # group 33 is www-data
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes:
      - name: grav-accounts
        persistentVolumeClaim:
          claimName: grav-accounts-pvc
      - name: grav-data
        persistentVolumeClaim:
          claimName: grav-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-accounts-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-data-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
