apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: grav-init-pwd
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: grav-init-pwd
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy