apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: ganache
  namespace: argocd
spec:
  destination:
    namespace: ganache
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
      targetRevision: master
      path: apps/ganache/staging/ingress.yml
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
      targetRevision: master
      path: apps/ganache/staging/pvc.yml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false