apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackqc2024
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hackqc2024
  source:
    repoURL: https://github.com/ClubCedille/hackqc2024
    path: k8s
    targetRevision: HEAD 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
