apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-cedille-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - secretName: wiki-tls
      hosts:
        - wiki.omni.cedille.club
  rules:
  - host: wiki.omni.cedille.club
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiki-cedille
            port:
              number: 80
