apiVersion: v1
kind: Service
metadata:
  name: trema
spec:
  ports:
    - name: trema
      targetPort: 6000
      protocol: TCP
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
