apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sandbox-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - user: svc-cedille-user
        email: cedille@etsmtl.net
  template:
    metadata:
      name: '{{.user}}-sandbox'
    spec:
      destination:
        namespace: '{{.user}}-sandbox'
        server: https://kubernetes.default.svc
      project: default
      sources:
        - chart: vcluster
          helm:
            releaseName: vcluster-sandbox
            valueFiles:
            - $values/system/vcluster/helm/common-values.yaml
          repoURL: https://charts.loft.sh
          targetRevision: 0.16.4
        - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
          targetRevision: master
          ref: values
        - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
          targetRevision: master
          path: system/sandboxes/namespaced
          kustomize:
            namePrefix: '{{.user}}-'
            patches:
              - patch: |-
                  - op: replace
                    path: /subjects/0/name
                    value: {{.email}}
                target:
                  kind: RoleBinding
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
