apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: netdata-claim
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: netdata
      path: kv/data/netdata/default/netdata
  output:
    name: netdata-claim
    stringData:
      NETDATA_CLAIM_TOKEN: '{{ .netdata.token }}'
      NETDATA_CLAIM_ROOMS: '{{ .netdata.rooms }}'
    type: Opaque