apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: applets-hello
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/role: "secret-reader"
        vault.hashicorp.com/agent-inject-template-redis-env: |
          {{- with secret "kv/applets/redis" -}}
          REDIS_PASSWORD={{ .Data.data.redis_password }}
          {{- end }}
    spec:
      serviceAccountName: secrets-reader
      containers:
        - name: redis
          image: redis:7.2.4
          ports:
            - containerPort: 6379
          command: ["/bin/sh", "-c"]
          args:
            - >
              source /vault/secrets/redis-env &&
              redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
