apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grav-acets
  name: grav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav-acets
  template:
    metadata:
      labels:
        app: grav-acets
    spec:
      containers:
      - name: grav-acets
        image: ghcr.io/clubcedille/grav:0.0.7
        imagePullPolicy: Always
        env:
        - name: GIT_VAULT_SECRET
          value: gitsync
        - name: ADMIN_VAULT_SECRET
          value: admin_pwd
        - name: HEAD_BRANCH
          value: test
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: grav-accounts
          mountPath: /var/www/html/user/accounts
        - name: grav-data
          mountPath: /var/www/html/user/data
      # group 33 is www-data
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes:
      - name: grav-accounts
        persistentVolumeClaim:
          claimName: grav-accounts-pvc
      - name: grav-configs
        persistentVolumeClaim:
          claimName: grav-configs-pvc
      - name: grav-data
        persistentVolumeClaim:
          claimName: grav-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-accounts-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-data-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
