apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-dronolab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: webapp=ghcr.io/dronolab/dronolab-website:latest
    argocd-image-updater.argoproj.io/webapp.update-strategy: digest
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-dronolab
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: apps/dronolab/webApp/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
