apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: integrale-website
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: website=ghcr.io/integrale-ets/site-integrale:latest
    argocd-image-updater.argoproj.io/website.update-strategy: digest
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: integrale-website
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: apps/integrale/website/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
