apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pixie-helm
  namespace: argocd
spec:
  destination:
    namespace: pl
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: pixie-operator-chart
      helm:
        releaseName: pixie-helm
        valueFiles:
        - $values/system/pixie/helm/values.yaml
      repoURL: https://artifacts.px.dev/helm_charts/operator
      targetRevision: 0.1.4
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
      targetRevision: master
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged