apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: randomsecret-password
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  path: kv/data/test/default/test
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
  isKVSecretsEngineV2: true
  connection:
    address: https://vault-0.vault-internal.vault.svc.cluster.local:8200
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: test-pass
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  path: kv/data/default/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
  isKVSecretsEngineV2: true
  refreshPeriod: 24h
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-test
spec:
  provider: vault
  parameters:
    roleName: secret-reader
    objects: |
      - objectName: "test-pass"
        secretPath: "kv/data/default/default/test-pass"
        secretKey: "password"

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-2
spec:
  containers:
  - image: jweissig/app:0.0.1
    name: webapp
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-test"