apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-helm
  namespace: argocd
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.13.2
    helm:
      releaseName: crossplane
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane
    project: platforme-cedille
  syncPolicy:
    syncOptions:
    - CreateNamespace=true