apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator
  namespace: argocd
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/ClubCedille/Plateforme-Cedille
      path: system/clickhouse/clickhouse-operator-resources
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: clickhouse-system
    project: platforme-cedille
  syncPolicy:
    syncOptions:
    - CreateNamespace=true