apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: opentelemetry
  namespace: argocd
spec:
  destination:
    namespace: opentelemetry-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: open-telemetry/opentelemetry-operator
      helm:
        releaseName: my-otel-demo
        valueFiles:
        - $values/system/opentelemetry/helm/otel-values.yaml
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.66.0
    - repoURL: 'https://github.com/ClubCedille/Plateforme-Cedille.git'
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged