apiVersion: apps/v1
kind: Deployment
metadata:
  name: calidum-rotae-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calidum-rotae-service
  template:
    metadata:
      labels:
        app: calidum-rotae-service
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/role: 'secret-reader'
        vault.hashicorp.com/agent-inject-template-calidum-rotae-service-env: |
          {{- with secret "kv/calidum-rotae/default/calidum-rotae-service-env" -}}
            export CALIDUM_ROTAE_SERVICE_API_KEY="{{ .Data.data.calidum_rotae_service_api_key }}"
          {{- end }}
    spec:
      containers:
      - name: calidum-rotae-service
        image: ghcr.io/clubcedille/calidum-rotae-service:0.0.1
        command:
          ['/bin/sh', '-c', 'source /vault/secrets/calidum-rotae-service-env && /calidum_rotae_service --port 3000 --discord_provider_hostname discord-provider-service --discord_provider_port 5000 --email_provider_hostname email-provider-service --email_provider_port 4000 --enable_otel_tracing true --otel_otlp_exporter_host opentelemetry-collector-collector-headless.opentelemetry-collector.svc.cluster.local  --otel_otlp_exporter_port 4318']
        ports:
        - containerPort: 3000