apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: raconteurs-

resources:
  - ../../../../bases/grav

 images:
 - name: ghcr.io/clubcedille/grav
   newTag: "1.7.45.1"

patches:
  - path: vault-patch.yaml
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: raconteurs.etsmtl.ca
      - op: replace
        path: /spec/tls/0/hosts/0
        value: raconteurs.etsmtl.ca
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/raconteurs-grav/default/grav
