apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-configs
  namespace: argocd
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/ClubCedille/Plateforme-Cedille
      path: system/vault/configs
      targetRevision: HEAD 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
    project: platforme-cedille
