apiVersion: v1
kind: Service
metadata:
  name: svc-wikijs-dronolab
  labels:
    app: wikijs-dronolab
spec:
  selector:
    app: wikijs-dronolab
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  clusterIP: None