apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: your-deployment-name
    patch: |-
      - op: replace
        path: /spec/template/spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"

# Define common and environment-specific configuration here