apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: integrale-

resources:
  - ../../../../bases/grav

patches:
  - path: vault-patch.yaml
  - target:
      kind: Ingress
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: integrale.etsmtl.ca
      - op: replace
        path: /spec/tls/0/hosts/0
        value: integrale.etsmtl.ca
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/integrale-grav/default/grav
