apiVersion: apps/v1
kind: Deployment
metadata:
  name: grav
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-template-gitsync: |
          {{- with secret "github/token/Integrale-grav" -}}
          enabled: true
          folders:
            - pages
            - plugins
            - themes
            - config
          SyncNotice: null
          sync:
            on_save: true
            on_delete: true
            on_media: true
            cron_enable: true
            cron_at: '*/10 * * * *'
          local_repository: null
          repository: 'https://github.com/ClubCedille/integrale.etsmtl.ca.git'
          no_user: '0'
          user: x-access-token
          password: "{{ .Data.token }}"
          webhook_enabled: '1'
          webhook: '/_git_webhook'
          branch: master
          remote:
            name: origin
            branch: master
          git:
            author: gitsync
            message: '(Grav GitSync) Automatic Commit'
            name: GitSync
            email: git-sync@trilby.media
            bin: git
            ignore: null
            private_key: null
          logging: true
          {{- end }}
        vault.hashicorp.com/agent-inject-template-admin_pwd: |
          {{- with secret "kv/data/Integrale-grav/default/grav/Integrale-grav-init-pwd" -}}
          state: enabled
          email: admin@integrale.etsmtl.ca
          username: admin
          fullname: admin
          title: Administrator
          access:
            admin:
              login: true
              super: true
            site:
              login: true
          password: "{{ .Data.data.password }}"
          {{- end }}
