apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/role: 'secret-reader'
        # https://github.com/ApplETS/Backend-Hello/blob/main/core/.env.template
        vault.hashicorp.com/agent-inject-template-hello-env: |
          {{- with secret "kv/applets-hello/default/hello-env" -}}
            export ASPNETCORE_HTTPS_PORT="{{ .Data.data.aspnetcore_https_port }}"
            export ASPNETCORE_HTTP_PORT="{{ .Data.data.aspnetcore_http_port }}"
            export ASPNETCORE_ENVIRONMENT="{{ .Data.data.aspnetcore_environment }}"
            export CONNECTION_STRING="{{ .Data.data.connection_string }}"
            export SUPABASE_PROJECT_ID="{{ .Data.data.supabase_project_id }}"
            export SUPABASE_SECRET_KEY="{{ .Data.data.supabase_secret_key }}"
            export SUPABASE_ANON_KEY="{{ .Data.data.supabase_anon_key }}"
            export EMAIL_SERVER="{{ .Data.data.email_server }}"
            export EMAIL_PORT="{{ .Data.data.email_port }}"
            export EMAIL_USERNAME="{{ .Data.data.email_username }}"
            export EMAIL_PASSWORD="{{ .Data.data.email_password }}"
            export EMAIL_FROM="{{ .Data.data.email_from }}"
            export EMAIL_TO_IF_DEBUG="{{ .Data.data.email_to_if_debug }}"
            export REDIS_CONNECTION_STRING="{{ .Data.data.redis_connection_string }}"
            export HOST_DIR="{{ .Data.data.host_dir }}"
            export CONTAINER_DIR="{{ .Data.data.container_dir }}"
            export CDN_URL="{{ .Data.data.cdn_url }}"
            export FRONTEND_BASE_URL="{{ .Data.data.frontend_base_url }}"
            export RATE_LIMIT_TIME_WINDOW_SECONDS="{{ .Data.data.rate_limit_time_window_seconds }}"
            export RATE_LIMIT_MAX_REQUESTS="{{ .Data.data.rate_limit_max_requests }}"
          {{- end }}
    spec:
      containers:
        - name: hello
          image: ghcr.io/applets/backend-hello:main
          imagePullPolicy: Always
          command: ['/bin/sh', '-c', '. /vault/secrets/hello-env && dotnet api.core.dll']
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: hello-volume
              mountPath: /app/volume
      volumes:
        - name: hello-volume
          persistentVolumeClaim:
            claimName: hello-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
