apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-example-data-storage-pv
  namespace: clickhouse-system
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/clickhouse
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-example-log-storage-pv
  namespace: clickhouse-system
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/clickhouse-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-1
