apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/ClubCedille/Plateforme-Cedille
      path: system/netdata/ressources
      targetRevision: feature/netdata
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netdata
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged