apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/ClubCedille/Plateforme-Cedille
      path: system/netdata/ressources
      targetRevision: feature/netdata
    - chart: netdata
      repoURL: https://netdata.github.io/helmchart
      targetRevision: 3.7.95
      helm:
        releaseName: netdata
        valuesObject:
          restarter:
            enabled: true
          parent:
            claiming:
              enabled: true
              envFrom:
              - secretRef:
                  name: netdata-claim
          child:
            claiming:
              enabled: true
              envFrom:
              - secretRef:
                  name: netdata-claim
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netdata
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged