apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-crabe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-crabe
  template:
    metadata:
      labels:
        app: webapp-crabe
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: webapp-crabe
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DATABASE_NAME
            - name: DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_DRIVER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: PASSWORD
            - name: PRODUCTION_MODE
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: PRODUCTION_MODE
            - name: PROD_HOST
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: PROD_HOST
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: USERNAME
          image: ghcr.io/crabe-etsmtl/crabe-atelier:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
