apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.0.1  
    path: system/grafana
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
