name: Demander un sandbox Kubernetes
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Main github email'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add user to sandbox list
        run: |
          yq eval '. += [{"user": "${{github.event.sender.login}}", "email": "${{github.event.inputs.email}}"}]' system/sandboxes/sandbox-list.yaml -i
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Create sandbox for ${{github.event.sender.login}}
          branch: sandbox/${{github.event.sender.login}}
          body: |
            @${{github.event.sender.login}}. Once this PR is merged, you will be able to login
            to your sandbox by following these steps:
            1. Go to https://cedille.omni.siderolabs.io/cluster/cedille-cluster/overview, click "Download kubeconfig" and put that file as ~/.kube/config
            2. Install vcluster on your computer: https://www.vcluster.com/docs/getting-started/setup
            3. run `vcluster connect vcluster-sandbox -n ${{github.event.sender.login}}-vcluster-sandbox`
            4. Start using kubectl to play around!