name: Build and Push Wiki Cedille Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
  pull_request:
    branches:
      - master
    paths:
      - 'wiki/**'

jobs:
  build-push-ghcr:
    uses: ClubCedille/cedille-workflows/.github/workflows/build-push-ghcr.yaml@master
    with:
      container-name: 'wiki-cedille'
      context: 'wiki'
      fille: Dockerfile
    secrets: inherit
